repos:
- repo: https://github.com/ambv/black
  rev: 23.7.0
  hooks:
  - id: black
- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
  - id: isort
- repo: https://github.com/pycqa/flake8.git
  rev: 6.1.0
  hooks:
  - id: flake8
